# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 563)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sidebar = QtWidgets.QWidget(self.centralwidget)
        self.sidebar.setGeometry(QtCore.QRect(0, 0, 541, 521))
        self.sidebar.setStyleSheet("background-color: #2596be")
        self.sidebar.setObjectName("sidebar")
        self.wid1 = QtWidgets.QWidget(self.sidebar)
        self.wid1.setGeometry(QtCore.QRect(49, 59, 211, 131))
        self.wid1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.wid1.setObjectName("wid1")
        self.pushButton = QtWidgets.QPushButton(self.wid1)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 161, 141))
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet("font: 16pt \"Comic Sans MS\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.wid1_2 = QtWidgets.QWidget(self.sidebar)
        self.wid1_2.setGeometry(QtCore.QRect(50, 200, 211, 131))
        self.wid1_2.setStyleSheet("background-color: rgb(250, 250, 250);")
        self.wid1_2.setObjectName("wid1_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.wid1_2)
        self.pushButton_2.setGeometry(QtCore.QRect(0, -10, 161, 151))
        self.pushButton_2.setStyleSheet("font: 16pt \"Comic Sans MS\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.wid1_3 = QtWidgets.QWidget(self.sidebar)
        self.wid1_3.setGeometry(QtCore.QRect(50, 340, 211, 131))
        self.wid1_3.setStyleSheet("background-color: rgb(255,255,255);")
        self.wid1_3.setObjectName("wid1_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.wid1_3)
        self.pushButton_3.setGeometry(QtCore.QRect(0, -10, 161, 151))
        self.pushButton_3.setStyleSheet("font: 16pt \"Comic Sans MS\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 20, 531, 481))
        self.tableWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tableWidget.setStyleSheet("font: 10pt \"Segoe Fluent Icons\";")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.mdiArea = QtWidgets.QMdiArea(self.centralwidget)
        self.mdiArea.setGeometry(QtCore.QRect(210, 50, 51, 431))
        self.mdiArea.setObjectName("mdiArea")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Neu Termin"))
        self.pushButton_2.setText(_translate("MainWindow", "Remove Termin"))
        self.pushButton_3.setText(_translate("MainWindow", "Update Termin"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Datum"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Uhr"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gift"))
